name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  stages:
    name: setup
    runs-on: ubuntu-latest  
    env: 
      PROJECT_NAME: 'bicdd'
      HARBOR_HOST: 'harbor.trssllc.com'
      HARBOR_PROJECT: 'rapid'
      HARBOR_REPO: "${{ env.HARBOR_HOST }}/${{ env.HARBOR_PROJECT }}/${{ env.$PROJECT_NAME }}"  
    steps:
        - uses: actions/checkout@v2

        - name: Setup Java JDK
          uses: actions/setup-java@v2.5.0
          with:
            distribution: 'adopt' 
            java-version: '8'

        - name: Setup Maven
          uses: stCarolas/setup-maven@v4.2    

        - name: testing snv
          run: echo ${{ env.HARBOR_REPO }}

  #   Publish to harbor - latest:
  #     runs-on: ubuntu-latest        

  #   Publish to harbor - CI:
  #     runs-on: ubuntu-latest     

  #   Publish to harbor - POM:
  #     runs-on: ubuntu-latest               

  #   Cleanup:
  #     runs-on: ubuntu-latest        


