name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  stages:
    name: build
    runs-on: ubuntu-latest  
    env: 
      PROJECT_NAME: 'bicdd'
      HARBOR_HOST: 'harbor.trssllc.com'
      HARBOR_PROJECT: 'rapid'
      HARBOR_REPO: 'harbor.trssllc.com/rapid/bicdd' 
      
    steps:
        - uses: actions/checkout@v2
        
        - name: Creating SetUp
          id: vars
          run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}
          
        - name: Check output
          run: echo ${{ steps.vars.outputs.short_ref }}

        - name: Setup Java JDK
          uses: actions/setup-java@v2.5.0
          with:
            distribution: 'adopt' 
            java-version: '8'

        - name: Setup Maven
          uses: stCarolas/setup-maven@v4.2    

#         - name: Publish to harbor - latest
#           run:       

#         - name: Publish to harbor - CI
#           run: |
#             docker tag ${{ env.PROJECT_NAME }}:latest ${{ env.HARBOR_REPO }}:${{ env.HARBOR_TAG }}
#             docker push ${{ env.HARBOR_REPO }}:${{ env.HARBOR_TAG }}
#             docker rmi ${{ env.HARBOR_REPO }}:${{ env.HARBOR_TAG }}

#         - name: Publish to harbor - POM
#           run:              

#         - name: Cleanup:
#           run:        


